version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "America/Santiago"
    open-pull-requests-limit: 20
    target-branch: "main"
    labels:
      - "dependencies"
